from consts.get_env import get_env

DISCORD_BOT_TOKEN = get_env('DISCORD_BOT_TOKEN')
SUPABASE_URL = get_env('SUPABASE_URL')
SUPABASE_KEY = get_env('SUPABASE_KEY')
OPENAI_API_KEY = get_env('OPENAI_API_KEY')
DISCORD_BOT_ID = 1181753278095167629
